### ISSUE TITLE
Make Betty rule and Valgrind rule

### ISSUE THREAD

**Issue by lhack-jpeg** [RubberizedDuck/holbertonschool-monty#4]
https://github.com/RubberizedDuck/holbertonschool-monty/blob/56823794ec6b51de1ff49452f713ff3eae43c7e3/Makefile#L13

**Comment by RubberizedDuck** [comment]
Added rulings for both Betty and Valgrind. Just need to add new rules to valgrind whenever we have a new .m (monty) file to test.
